version: '3.8'

services:
  mysqldb:
    image: mysql:8.0.43
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Vinfast_db
    ports:
      - "3306:3306"
    volumes:
      # --- SỬA CHỖ NÀY (Dòng 15-16) ---
      # Gắn volume ID cũ vào đường dẫn /var/lib/mysql trong container
      - bc81c12f198b607c79d09d182b4c1aa1c6545be8b88242330799c70ef6594dc0:/var/lib/mysql
    networks:
      - app-network

  # --- Service 2: Backend (Đã bỏ environment) ---
  backend-service:
    container_name: backend-container
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    # ĐÃ XÓA PHẦN ENVIRONMENT Ở ĐÂY
    networks:
      - app-network

  # --- Service 3: Frontend ---
  frontend-service:
    container_name: frontend-container
    build: ./frontend/vue-app
    ports:
      - "3000:80"
    depends_on:
      - backend-service
    networks:
      - app-network

volumes:
  # Khai báo cho Docker biết volume này đã tồn tại, không được xóa!
  bc81c12f198b607c79d09d182b4c1aa1c6545be8b88242330799c70ef6594dc0:
    external: true

networks:
  app-network:
    driver: bridge