version: '3.8'
services:
  mysql-shop:
    image: mysql:8.0
    container_name: shop_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop_demo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: