server:
  port: 8080
  address: 0.0.0.0
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vinfast_db_new
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600
  refreshable-duration: 36000

# VNPAY Config (Sửa lại đúng chuẩn YAML)
vnp:
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  tmnCode: BXD54CA9  # Điền mã TmnCode của bạn
  hashSecret: M9L24LRC0DG2JO4N4B1HEZP5TFS91L45 # Điền HashSecret của bạn
  apiUrl: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
  returnUrl: http://localhost:3000/payment-callback